{% set data = load_setup_py_data() %}

package:
    name: sfdata
    version: {{ data["version"] }}

about:
   home: {{ data["url"] }}
   summary: {{ data["description"] }}

source:
    path: ..

build:
  noarch: python

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - h5py
        - numpy
        - pandas
        - tqdm


